http:
  port: "8081"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"

accounts:
  endpoints:  "module4-proxy-ap.us-e2.cloudhub.io"
  protocol: "HTTP"
  port: "80"
  client_id:  "4b7508ae217c46a594873072d265cd22"
  client_secret:  "7d63790Ab20f42DB9e53667fB12a4BAf"